# Generated by Django 3.2.9 on 2022-01-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudappmysql', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crudtb2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoid', models.IntegerField()),
                ('snameid', models.IntegerField()),
                ('semailid', models.IntegerField()),
            ],
        ),
    ]
